#version: '3.8'
services:
  app:
    build: .
    container_name: news-crawler
    depends_on:
      - rabbitmq
      - elasticsearch
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - ELASTICSEARCH_HOST=elasticsearch
    ports:
      - "8080:8080"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
